### ISSUE TITLE
Version details and explanation

### ISSUE THREAD

**Issue by alexvdvalk** [bullhorn/novo-elements#1141]
**Describe the bug**
Currently, the novo-elements package has 2 versions that are being developed. I'm looking for some guidance on which is the better version to use in my projects, and also any details on why there are two versions being developed. 

Additionally, can you provide information on which version the demos (https://bullhorn.github.io/novo-elements/) are based on?

**Comment by tbo47** [comment]
We have different versions because some projects take more time than other to update.

The latest version ([4.3.9](https://github.com/bullhorn/novo-elements/blob/master/projects/novo-elements/package.json#L3)) is the latest and the one recommended.

The demo website is generated from the branch `master` each time there is a commit on the branch.
