### ISSUE TITLE
Address Block Field Interactions

### ISSUE THREAD

**Issue by miola03** [bullhorn/novo-elements#1146]
**Would like the ability to manipulate Address Block fields with field interactions. These fields don’t seem to have their own data control key nor do they seem to fire off code that is written against them.**

For example – I want to write a field interaction that loads in the City and State on the Contact’s address when the contact is being added from a company record but wipe out the street address (address1), Building/Apt (address2) and potentially zip code (zip) so the user has to fill that in themselves. Seems I can only manipulate the Address Block as a whole (address) since that is the only field on the back end that is associated to a data-control-key

**Will this feature require a breaking change?**
Does your feature request require breaking changes to existing functionality of current components or services?
- [ ] Yes
- [ ] No
- [x ] Not sure

**Additional context**
[Address Block Field Interactions.docx](https://github.com/bullhorn/novo-elements/files/5630217/Address.Block.Field.Interactions.docx)

**Comment by jeremybradbury** [comment]
so i confirmed that watching any of these fields for onchange, don't seem to fire: fullAddress, address1, address2, city, state, zip.

i tried init instead of change and on-init to true and deployed only a console log. and it never fires with the above fields.

however when i change the field name to description, it fires onchange and oninit as expected.

the object this was on: Location (aka LocationVersion).

I have tried adding it to a page interaction presave, but it doesn't seem to work either (I'll update this if it does). 

am I missing something or this just an open bug (or missing feature)?

is there a known workaround?

**Comment by michael-amaya-bh** [comment]
Closing as there is a known workaround and the address block is not being considered to be merged into our design system at this time.
