### ISSUE TITLE
[Toasts] - Animations

### ISSUE THREAD

**Issue by jgodi** [bullhorn/novo-elements#45]
Currently, the toast will animate down and if the toast is of the same type it will animate down correctly. However, if you have toasts that are different they still animate down. Video url below:

http://recordit.co/0zU49Usdmu

**Comment by asibilia** [comment]
`.class-name:last-of-type(n)` is currently not supported in CSS. The fix for this requires adding specific "index classes" (ie. `.growl-top-right-1`) via javascript and styling them appropriately. Rather than do that, I suggest we wait for `ng-animate-2` and fix it when the animations are written with `ng-animate`

**Comment by jgodi** [comment]
Agreed!

**Comment by jgodi** [comment]
@asibilia The new NG Animate module is now included!
