### ISSUE TITLE
[Form] Non-dynamic forms do not have `showOnlyRequired`

### ISSUE THREAD

**Issue by BRS999** [bullhorn/novo-elements#541]
Hello!

So I'm working on that static form but not sure how to correctly validate it.

I see in the examples you have a save method like:

```
   save(form) {
        if (!form.isValid) {
            form.showOnlyRequired(true);
        } else {
            alert('SAVING');
        }
    }
```
When I implement something similar I get an error saying showOnlyRequired is not a function.

I understand the error message but not sure of the correct approach. 

What I'd like to do is check if the form is valid and if so process it. 

If not, display the required fields.

How can I accomplish this?

Thanks again!

-Ben

**Comment by amrutha-rajiv** [comment]
Hi Ben,

In our example, we pass an instance of the form into the save method this way (note the variable assignment of `myform` on the `novo-dynamic-form` component tag - 

![image](https://user-images.githubusercontent.com/1760101/29888007-56ea020e-8d8d-11e7-84ab-ad9af3dc99b5.png)

If this doesn't help, can you please send us your template and component code so that we can understand the issue better?

Thanks,
Amrutha

**Comment by jgodi** [comment]
`showOnlyRequired` is only a function on our `<novo-dynamic-form>`. The only reason that it works is because the entire form is driven off our Entity model. So each field is dynamically created and we can control that easily.

Since you are probably using the static form option `<novo-form>` you will not get access to this method because you are hardcoding each of your fields. 

We could probably add a method like that on our `<novo-form>` component or you could manually hide/show fields via `*ngIf`. 

I will convert this to a bug to add that missing method for now.

**Comment by BRS999** [comment]
Thank you both for the quick response.

**Comment by jgodi** [comment]
Added via https://github.com/bullhorn/novo-elements/commit/1359cc773a395c2250633a12a717a6db676efde7. You can view it in the first example on http://bullhorn.github.io/novo-elements/#/form.
