### ISSUE TITLE
[Question] AppBridge issue and S-Release

### ISSUE THREAD

**Issue by BRS999** [bullhorn/novo-elements#592]
Hello!

I'm having an issue with S-Release and app bridge. 

App bridge is working correctly in Novo, but not in S-Release.

I get the error `win is null` in FF and `cannot read property windowid of null` in Chrome.

Any suggestions?

**Comment by jgodi** [comment]
What methods are you using from AppBridge and expecting to you in S-Release?

Also, do you know what version of S-Release you are currently on? If no, at least what swimlane you are hitting?

Thanks!

**Comment by BRS999** [comment]
Hello!

I believe we're running into trouble registering.

We're trying to use httpPost, and httpGet.

The swimlane is cls20. 

Let me know if you need more info!

**Comment by BRS999** [comment]
It seems the registration is working but the bridge method calls are not.

Here's an example of a call I'm making.

```
bridge.httpPOST(`entity/Task/${BHTask.id}`, JSON.stringify(BHTask))
      .then( response => {
        bridge.httpGET(`entity/Task/${response.data.changedEntityId}?fields=*`)
        .then(r => {
```

**Comment by rnitu** [comment]
Hello Joshua,

I work with Ben. As an iframe in Novo, all Appbridge calls work. In S release, seems like we can 'GET', as we can open tabs, however, when we attempt other CRUD operations, we receive the error below.

The only difference in the request we can notice is in the request content-type (Novo:  content-type: text/plain; S Release:  Content-Type: application/json;charset=UTF-8). 

If we perform the request using postman with the same information, as well as content-type, the operation completed successfully (even with the extra ampersand that shows in the PUT request).  

**Here is the request body:**
`{"action":"Connect","comments":"test","personReference":{"id":5355337},"commentingPerson":{"id":5429246}} `

**Here is the request header:**
PUT /core/entity/Note?&BhRestToken={our token} HTTP/1.1 
Host: cls20.bullhornstaffing.com 
Connection: keep-alive 
Content-Length: 120 
Origin: https://cls20.bullhornstaffing.com 
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36 
Content-Type: application/json;charset=UTF-8 
Accept: */* 
Referer: https://cls20.bullhornstaffing.com/BullhornSTAFFING/MainFrame.jsp? 
Accept-Encoding: gzip, deflate, br 
Accept-Language: en-US,en;q=0.9 

**Here is the response:**
`{"errorMessage":"No content to map to Object due to end of input","errorCode":400}`

Hope this information helps

**Comment by jgodi** [comment]
I will take a look at this today. Thanks for the info!

**Comment by rnitu** [comment]
Thank you so much!
Robert Nitu | Manager, Innovation & Development | 24 Seven
41 Madison Avenue, 37th Floor | New York, New York 10010 | www.24seventalent.com
Office: 212.966.4426 | Direct: 646.937.6997

[24 Seven]<www.24seventalent.com>
Find us online: Twitter<http://twitter.com/24Seventalent> | Facebook<http://www.facebook.com/pages/24-Seven/22164072443?ref=s> | LinkedIn<https://www.linkedin.com/company/17937>

We want to hear from you! Take our 2018 Job Market Survey.<https://inavero.qualtrics.com/jfe/form/SV_3NMkIGunrduAZtX?link=2>
________________________________
This message contains information which may be confidential and privileged. Unless you are the addressee (or authorized to receive for the addressee), you may not use, copy, re-transmit, or disclose to anyone the message or any information contained in the message. If you have received the message in error, please advise the sender by reply e-mail @24seveninc.com, and delete the message. E-mail communication is highly susceptible to spoofing, spamming, and other tampering, some of which may be harmful to your computer. If you are concerned about the authenticity of the message or the source, please contact the sender directly.
________________________________

**Comment by jgodi** [comment]
Can you try to not `JSON.stringify` the data, you should be sending the full object.

**Comment by rnitu** [comment]
That worked! Thank you so much!

**Comment by jgodi** [comment]
Awesome! Glad to hear it!
