### ISSUE TITLE
Row count for a Novo Table

### ISSUE THREAD

**Issue by BRS999** [bullhorn/novo-elements#666]
Hello again!

Is there a way to grab the current row count in a table? For instance, if I filter based on a date and 3 rows show up, I'd like to display the current row count.

Is this possible?

Thanks,

Ben

**Comment by jgodi** [comment]
If you are using a DataProvider for this, you can get the count for it that way. Otherwise you will have to make a local reference to the table and grab it in your class. Then use the DataProvider it sets up for you to get the total.

https://github.com/bullhorn/novo-elements/blob/master/src/platform/elements/table/Table.ts#L374

**Comment by BRS999** [comment]
Thank you for the response. I'm a bit confused still. It's probably something simple.

I believe I am using the dataprovider. I set up the table like this:

`<novo-table [dataProvider]="rows" [columns]="columns" [config]="config">`

With the rows, columns, etc providing the proper information.

I see the get dataprovider method, but I'm not clear on how I can grab that in order to update the rows. 

Can you help clarify? 

Thanks!

**Comment by jgodi** [comment]
`rows` in this case is an array?

You can store a local reference to the table via:

`<novo-table blah... #table>`

And then use that reference to get the count via `<span>Total Rows: {{ table.total }}</span>`

Hope that helps!

**Comment by BRS999** [comment]
Awesome. Makes sense. Thank you!
